# Etapa 1: compilamos la app de SvelteKit
FROM node:20-alpine AS build
WORKDIR /app

ENV PNPM_HOME="/pnpm" \
    PATH="$PNPM_HOME:$PATH" \
    COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable pnpm && pnpm config set store-dir /pnpm/store
COPY package.json pnpm-lock.yaml* ./
COPY .npmrc ./
RUN pnpm install --frozen-lockfile
COPY . .

# Declarar todas las variables públicas que usa SvelteKit
ARG PUBLIC_BD_URL
ARG PUBLIC_BD_API
ARG PUBLIC_INGRESO_URL
ARG PUBLIC_PAGOS_URL
ARG PUBLIC_FORM_PAGOS_URL
ARG PUBLIC_USERS_FORM
ARG PUBLIC_USER_UPDATE
ARG PUBLIC_SEND_CODE_URL
ARG PUBLIC_CUSTOM_VARS
ARG PUBLIC_CLIENT
ARG PUBLIC_GET_INGRESOS_URL
ARG PUBLIC_UPDATE_INGRESO_URL
ARG PUBLIC_API_URL

# Exportarlas al entorno para el build
ENV PUBLIC_BD_URL=${PUBLIC_BD_URL}
ENV PUBLIC_BD_API=${PUBLIC_BD_API}
ENV PUBLIC_INGRESO_URL=${PUBLIC_INGRESO_URL}
ENV PUBLIC_PAGOS_URL=${PUBLIC_PAGOS_URL}
ENV PUBLIC_FORM_PAGOS_URL=${PUBLIC_FORM_PAGOS_URL}
ENV PUBLIC_USERS_FORM=${PUBLIC_USERS_FORM}
ENV PUBLIC_USER_UPDATE=${PUBLIC_USER_UPDATE}
ENV PUBLIC_SEND_CODE_URL=${PUBLIC_SEND_CODE_URL}
ENV PUBLIC_CUSTOM_VARS=${PUBLIC_CUSTOM_VARS}
ENV PUBLIC_CLIENT=${PUBLIC_CLIENT}
ENV PUBLIC_GET_INGRESOS_URL=${PUBLIC_GET_INGRESOS_URL}
ENV PUBLIC_UPDATE_INGRESO_URL=${PUBLIC_UPDATE_INGRESO_URL}
ENV PUBLIC_API_URL=${PUBLIC_API_URL}


RUN echo "🔍 Variables disponibles en build:" && env | grep PUBLIC_

RUN pnpm build

# Etapa 2: imagen final mínima con nginx
FROM nginx:1.27-alpine-slim AS runtime
ENV NODE_ENV=production
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
